shim-version: v0.3.18@sha256:7d9f98be78c91ede89f43c948a12d084fae34312effe9395ca7ed572991cb561
cvm-version: 0.7.5
cpus: 2
memory: 4096

containers:
  - name: "tinfoil-buckets"
    image: "ghcr.io/tinfoilsh/tinfoil-buckets@sha256:34f16e4c4a1faa316a02c6040006a860cea68d38ba0376b5aa8090a6b27be2ff" # v0.0.3
    env:
      - R2_BUCKET_NAME: "tinfoil-bucket"
    secrets:
      - CLOUDFLARE_ACCOUNT_ID
      - R2_TINFOIL_BUCKET_ACCESS_KEY_ID
      - R2_TINFOIL_BUCKET_SECRET_ACCESS_KEY

shim:
  listen-port: 443
  upstream-port: 8089
  paths:
    - /items/*
    - /mcp
    - /health
