cvm-version: 0.10.1
cpus: 2
memory: 4096

containers:
  - name: "tinfoil-buckets"
    image: "ghcr.io/tinfoilsh/tinfoil-buckets@sha256:3fb70f811789fb02cf19a147993132cb754ff42ba71b7adba029ef34a9c37182" # v0.0.7
    env:
      - R2_BUCKET_NAME: "tinfoil-bucket"
      - CONTROL_PLANE_URL: "https://api.tinfoil.sh"
      - USAGE_REPORTER_ID: "tinfoil-buckets"
    secrets:
      - CLOUDFLARE_ACCOUNT_ID
      - R2_TINFOIL_BUCKET_ACCESS_KEY_ID
      - R2_TINFOIL_BUCKET_SECRET_ACCESS_KEY
      - USAGE_REPORTER_SECRET

shim:
  listen-port: 443
  upstream-port: 8089
  paths:
    - /items/*
    - /mcp
    - /health
  authenticated: true
  authenticated-endpoints:
    - /items/*
