cvm-version: 0.10.1
cpus: 2
memory: 4096

networks:
  public:
    egress: open

containers:
  - name: "tinfoil-buckets"
    image: "ghcr.io/tinfoilsh/tinfoil-buckets@sha256:216b1f9e880b3f268a7dfe8383d95d95a1a31843268661363e58f54272e06986" # v0.0.8
    networks: [public]
    env:
      - R2_BUCKET_NAME: "tinfoil-bucket"
      - CONTROL_PLANE_URL: "https://api.tinfoil.sh"
      - USAGE_REPORTER_ID: "tinfoil-buckets"
    secrets:
      - CLOUDFLARE_ACCOUNT_ID
      - R2_TINFOIL_BUCKET_ACCESS_KEY_ID
      - R2_TINFOIL_BUCKET_SECRET_ACCESS_KEY
      - USAGE_REPORTER_SECRET

shim:
  listen-port: 443
  upstream-port: 8089
  paths:
    - /items/*
    - /mcp
    - /health
  authenticated: true
  authenticated-endpoints:
    - /items/*
